version: "3.8"

services:
  api:
    build: .
    container_name: pa-api-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      minio:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=adminpassword
      - MINIO_BUCKET_NAME=youtube-mp3
    volumes:
      - ./downloads:/tmp
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpassword
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 admin adminpassword;
      mc ls myminio/youtube-mp3 || mc mb myminio/youtube-mp3;
      mc anonymous set public myminio/youtube-mp3;
      exit 0;
      "
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  minio-data:
