version: "3.8"

services:
  api:
    build: .
    container_name: pa-api-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - minio
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - MINIO_ENDPOINT=minio
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=adminpassword
      - MINIO_BUCKET_NAME=youtube-mp3
    volumes:
      - ./downloads:/tmp
    networks:
      - backend

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API do MinIO
      - "9001:9001"  # Painel de Administração do MinIO
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpassword
    volumes:
      - minio-data:/data
    command: server --console-address ":9001" /data
    networks:
      - backend

  minio-create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      mc alias set myminio http://minio:9000 admin adminpassword;
      mc mb myminio/youtube-mp3;
      mc policy set public myminio/youtube-mp3;
      exit 0;
      "
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  minio-data:
